const CONFIG = {
  LOGIN_API: '/api/login',
  // Se cambian las URLs remotas por endpoints locales proxy
  SETUP_API: '/api/setup',
  GRID_API_BASE: '/api/listas',

  LISTAS: {
    canales: 68,
    radios: 221,
    camaras: 139,
    peliculas: 250,
  },
  CATEGORY_LABELS: {
    canales: 'Canales',
    radios: 'Radios',
    camaras: 'Cámaras',
    peliculas: 'Películas',
  },
  CATEGORY_ORDER: ['canales', 'radios', 'camaras', 'peliculas'],

  SESSION_API: '/api/sesiones',
  DOMINIO: 'lua',
  SESSION_RENEW_MARGIN_MS: 10 * 60 * 1000,
  STREAM_RENEW_MARGIN_MS: 8 * 60 * 1000,
  MAX_STREAM_RETRY: 3,
  STORAGE_KEYS: {
    usuario: 'antel_usuario',
    password: 'antel_password_b64',
    lastChannel: 'antel_ultimo_canal',
    order: 'antel_orden_canales',
  },

  EXCLUDED_CHANNELS: [],

  CHANNEL_PRIORITY_ORDER: [
    'Antel TV internacional',
    'Antel TV internacional 2',
    'Antel TV Internacional 1',
    'Inti',
    'ABC',
    'Mi móvil TV',
    'Siemprecine',
    'Cardinal',
    'Cardinal TV',
    'UCL',
    'Canal 4',
    'Canal 5',
    'VTV',
    'VTV Plus',
    'VTV Futbol',
    'VTV Futbol 2',
    'TV Ciudad',
    'A+V',
    'Canal 7 Punta',
    'Canal 2 Lascano',
    '9 de Rocha',
    'DW',
    'France 24',
    'CGTN',
    'RT',
    'Telesur',
  ],
};
